version: 2.1
jobs:
  preview_deployment:
    docker:
      - image: cimg/node:20.5.0
    environment:
      VERCEL_ORG_ID: $VERCEL_ORG_ID
      VERCEL_PROJECT_ID: $VERCEL_PROJECT_ID
    steps:
      - checkout
      - run:
          name: Install Vercel CLI
          command: sudo npm install --global vercel@latest
      - run:
          name: Pull Vercel Environment Information
          command: sudo vercel pull --yes --environment=preview --token=2rMHPBiUSYJYte7KufG2nZhF
      - run:
          name: Build Project Artifacts
          command: sudo vercel build --token=2rMHPBiUSYJYte7KufG2nZhF
      - run:
          name: Deploy Project Artifacts to Vercel
          command: sudo vercel deploy --prebuilt --token=2rMHPBiUSYJYte7KufG2nZhF

  production_deployment:
    docker:
      - image: cimg/node:20.5.0
    environment:
      VERCEL_ORG_ID: $VERCEL_ORG_ID
      VERCEL_PROJECT_ID: $VERCEL_PROJECT_ID
    steps:
      - checkout
      - run:
          name: Install Vercel CLI
          command: sudo npm install --global vercel@latest
      - run:
          name: Pull Vercel Environment Information
          command: sudo vercel pull --yes --environment=production --token=2rMHPBiUSYJYte7KufG2nZhF
      - run:
          name: Build Project Artifacts
          command: sudo vercel build --prod --token=2rMHPBiUSYJYte7KufG2nZhF
      - run:
          name: Deploy Project Artifacts to Vercel
          command: sudo vercel deploy --prebuilt --prod --token=2rMHPBiUSYJYte7KufG2nZhF

workflows:
  version: 2
  preview_and_production:
    jobs:
      - preview_deployment:
          filters:
            branches:
              ignore: /main/
      - production_deployment:
          filters:
            branches:
              only: /main/